{% set version = "3.4.1" %}

package:
  name: ffmpeg
  version: {{ version }}

source:
  fn: ffmpeg-{{ version }}.tar.gz  # [not win]
  url: https://ffmpeg.org/releases/ffmpeg-{{ version }}.tar.gz  # [not win]
  sha256: 3b6824f2c3ddd6bde37b82f76c679867f5c18d0c040cea222afd93aac9bf7ad2  # [not win]

  fn: ffmpeg-{{ version }}-win32-shared.zip  # [win32]
  url: https://ffmpeg.zeranoe.com/builds/win32/shared/ffmpeg-{{ version }}-win32-shared.zip  # [win32]
  sha256: 74628044181069d9ea9967a64c196418d1b1d04f724499845a2f36dbf1371d93  # [win32]

  fn: ffmpeg-{{ version }}-win64-shared.zip  # [win64]
  url: https://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-{{ version }}-win64-shared.zip  # [win64]
  sha256: 14eca81117af4c081d820d5bb669437ac9380060feaecb1d438188daf3eaca96  # [win64]

build:
  number: 3

requirements:
  build:
    - toolchain    # [not win]
    - pkg-config   # [not win]
    - libtool      # [not win]
    - yasm         # [not win]
    - bzip2 1.0.*  # [not win]
    - freetype 2.8.1     # [not win]
    - libiconv 1.15     # [not win]
    - x264 1!152.*         # [not win]
    - zlib 1.2.11   # [not win]
    - gnutls       # [not win]
    - 7za          # [win]
    - curl >=7.44.0,<8         # [win]
    - openssl      # [win]
  run:
    - bzip2 1.0.*  # [not win]
    - freetype 2.8.1     # [not win]
    - libiconv 1.15     # [not win]
    - x264 1!152.*         # [not win]
    - zlib 1.2.11   # [not win]
    - gnutls       # [not win]

test:
  commands:
    - ffmpeg --help
    - ffmpeg -codecs | grep "DEVI.S zlib"  # [unix]
    - ffmpeg -protocols | grep "https"  # [not win]
    # Verify dynamic libraries on all systems
    {% set ffmpeg_libs = [
        "avcodec",
        "avdevice",
        "swresample",
        "postproc",
        "avfilter",
        "swresample",
        "avcodec",
        "avformat",
        "swscale",
        "avresample"
    ] %}
    {% for each_ffmpeg_lib in ffmpeg_libs %}
    - test -f $PREFIX/lib/lib{{ each_ffmpeg_lib }}.dylib  # [osx]
    - test -f $PREFIX/lib/lib{{ each_ffmpeg_lib }}.so     # [linux]
    {% endfor %}
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.ffmpeg.org/
  license: GPL 3
  license_file: COPYING.GPLv3  # [unix]
  summary: Cross-platform solution to record, convert and stream audio and video.

extra:
  recipe-maintainers:
    - danielballan
    - jakirkham
    - 183amir
    - caspervdw
    - patricksnape
    - ocefpaf
    - sdvillal
